# Generated by Django 3.0.4 on 2020-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='huj',
            field=models.ManyToManyField(blank=True, related_name='_profile_huj_+', to='users.Profile'),
        ),
    ]
