# Generated by Django 3.0.4 on 2020-03-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_huj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='huj',
        ),
    ]
