# Generated by Django 3.0.2 on 2020-03-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200308_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_timestamp',
            field=models.DateField(blank=True),
        ),
    ]
