# Generated by Django 3.0.2 on 2020-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scrub_schroob',
            field=models.PositiveIntegerField(default=12, verbose_name=1),
            preserve_default=False,
        ),
    ]
