# Generated by Django 3.0.4 on 2020-03-14 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0017_auto_20200312_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^[a-zA-Z_]*[a-zA-Z]+[a-zA-Z_]*$', 'Only letters are allowed.')])),
                ('posts', models.ManyToManyField(blank=True, related_name='hashtags', to='post.Post')),
            ],
        ),
    ]
