# Generated by Django 3.0.4 on 2020-03-16 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20200316_0947'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='post_hashtags', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^[a-zA-Z_-]*[a-zA-Z]+[a-zA-Z_-]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='profile_hashtags', to='post.Post'),
        ),
    ]
