# Generated by Django 3.0.2 on 2020-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scrub_schroob',
            field=models.PositiveIntegerField(choices=[(1, 2), (3, 5)]),
        ),
    ]
