# Generated by Django 3.0.2 on 2020-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200210_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='chuj do dupy'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scrub_schroob',
            field=models.PositiveIntegerField(choices=[('ci', 2), (3, 'na imie'), ('asd', 'chuj')], default=('asd', 3, 'na imie'), help_text='13 Character <li> <a href="https://www.pornhub.com">ISBN number</a><br>chuj</li>'),
        ),
    ]
